# Generated by Django 4.2.26 on 2025-11-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=10)),
                ('lead_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=50)),
                ('project_name', models.CharField(max_length=255)),
                ('unit_type', models.CharField(max_length=100)),
                ('min_budget', models.FloatField()),
                ('max_budget', models.FloatField()),
                ('lead_status', models.CharField(max_length=100)),
                ('last_conversation_date', models.DateField(blank=True, null=True)),
                ('last_conversation_summary', models.TextField(blank=True)),
            ],
        ),
    ]
