# Generated by Django 4.2.26 on 2025-11-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='max_budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='min_budget',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
