# Generated by Django 4.2.26 on 2025-11-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0003_alter_lead_country_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('message_channel', models.CharField(choices=[('Email', 'Email'), ('WhatsApp', 'WhatsApp')], max_length=20)),
                ('sales_offer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leads', models.ManyToManyField(related_name='campaigns', to='agent_app.lead')),
            ],
        ),
    ]
