# Generated by Django 4.2.26 on 2025-11-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0004_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('Email', 'Email'), ('WhatsApp', 'WhatsApp')], max_length=20)),
                ('message_body', models.TextField()),
                ('status', models.CharField(default='generated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent_app.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent_app.lead')),
            ],
        ),
    ]
