# Generated by Django 4.2.26 on 2025-11-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_app', '0007_messagelog_campaignlead'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignlead',
            name='proposed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaignlead',
            name='proposed_time_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
